name: mailersend_api
description: A Dart package to send emails and manage communication using the MailerSend API.
version: 0.1.0+1


environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
dependencies:
  dio: ^5.7.0
  test: ^1.25.12
